export const mockedData = {
  formData: {
    id: 1,
    formCoverage: 'workersCompensation',
    name: "Worker's compensation applixation",
    steps: [
      {
        title: 'Who is the primary contact for this policy?',
        subtitle:
          "This person will receive all communications from Newfront about this policy. You can change this contact information later. If you're not sure, just add your contact information",
        questions: [
          {
            defaultValue: '',
            description: '',
            displayOrder: 1,
            fieldName: 'fullName',
            id: 1,
            isCustomField: false,
            isSharedField: false,
            label: 'Full Name',
            options: null,
            placeholder: '',
            required: true,
            type: 'text',
            value: '',
            validation: {
              inputType: 'string',
              isInputNullable: true,
              required: true,
            },
          },
          {
            defaultValue: '',
            description: '',
            displayOrder: 2,
            fieldName: 'role',
            id: 2,
            isCustomField: false,
            isSharedField: false,
            label: 'Role',
            options: null,
            placeholder: '',
            required: false,
            type: 'text',
            value: '',
            validation: {},
          },
          {
            defaultValue: '',
            description: '',
            displayOrder: 3,
            fieldName: 'phone',
            id: 3,
            isCustomField: false,
            isSharedField: false,
            label: 'Phone Number',
            options: null,
            placeholder: '',
            required: true,
            type: 'number',
            value: '',
            validation: {
              inputType: 'number',
              isInputNullable: true,
              required: true,
            },
          },
        ],
      },
      {
        title: 'Tell us about your company',
        subtitle: '',
        questions: [],
      },
    ],
  },
};
